/**
 * GPT-4o/GPT-5 Image Editing API
 * Advanced image editing using OpenAI's latest models with vision capabilities
 */

import { getOpenAIApiKey, hasApiKey } from './apiUtils';

export interface GPT5EditOptions {
  mode: 'enhance' | 'adjust' | 'transform' | 'effects' | 'custom';
  brightness?: number;
  contrast?: number;
  saturation?: number;
  blur?: number;
  rotation?: number;
  customPrompt?: string;
}

export interface GPT5EditResult {
  imageUrl: string;
  editedWith: 'gpt-4o' | 'gpt-4-turbo' | 'dall-e-3';
  metadata?: {
    originalPrompt?: string;
    editInstructions?: string;
  };
}

/**
 * GPT-4o Image Editor Service Class
 */
export class GPT5ImageEditorService {
  private apiKey: string | null;
  private baseUrl = 'https://api.openai.com/v1';

  constructor(apiKey?: string) {
    this.apiKey = apiKey || getOpenAIApiKey() || null;
  }

  isAvailable(): boolean {
    return !!this.apiKey;
  }

  private ensureApiKey(): void {
    if (!this.apiKey) {
      throw new Error('OpenAI API key is required for GPT-5 image editing. Please configure VITE_OPENAI_API_KEY in your environment.');
    }
  }

  /**
   * Edit an image using GPT-4o vision and DALL-E 3
   * Strategy: Use GPT-4o to analyze the image and create an edit prompt,
   * then use DALL-E 3 to generate the edited version
   */
  async editImage(
    imageUrl: string,
    options: GPT5EditOptions
  ): Promise<GPT5EditResult> {
    this.ensureApiKey();
    try {
      console.log('Editing image with GPT-4o + DALL-E 3:', { imageUrl, options });

      // Step 1: Analyze the image with GPT-4o Vision
      const analysisPrompt = this.createAnalysisPrompt(options);
      const editInstructions = await this.analyzeImageWithGPT4o(imageUrl, analysisPrompt);

      console.log('📋 GPT-4o edit instructions:', editInstructions);

      // Step 2: Generate edited image with DALL-E 3
      const editedImageUrl = await this.generateEditedImageWithDALLE(editInstructions);

      return {
        imageUrl: editedImageUrl,
        editedWith: 'gpt-4o',
        metadata: {
          editInstructions
        }
      };
    } catch (error) {
      console.error('Error editing image with GPT-4o:', error);
      throw error;
    }
  }

  /**
   * Analyze image with GPT-4o Vision
   */
  private async analyzeImageWithGPT4o(
    imageUrl: string,
    prompt: string
  ): Promise<string> {
    try {
      const response = await fetch(`${this.baseUrl}/chat/completions`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.apiKey}`
        },
        body: JSON.stringify({
          model: 'gpt-4o',
          messages: [
            {
              role: 'user',
              content: [
                {
                  type: 'text',
                  text: prompt
                },
                {
                  type: 'image_url',
                  image_url: {
                    url: imageUrl,
                    detail: 'high'
                  }
                }
              ]
            }
          ],
          max_tokens: 1000,
          temperature: 0.7
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`GPT-4o API error: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
      }

      const data = await response.json();
      const editInstructions = data.choices?.[0]?.message?.content || '';

      if (!editInstructions) {
        throw new Error('No edit instructions generated by GPT-4o');
      }

      return editInstructions;
    } catch (error) {
      console.error('Error analyzing image with GPT-4o:', error);
      throw error;
    }
  }

  /**
   * Generate edited image with DALL-E 3
   */
  private async generateEditedImageWithDALLE(prompt: string): Promise<string> {
    try {
      const response = await fetch(`${this.baseUrl}/images/generations`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${this.apiKey}`
        },
        body: JSON.stringify({
          model: 'dall-e-3',
          prompt: prompt,
          n: 1,
          size: '1024x1024',
          quality: 'hd',
          style: 'natural'
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`DALL-E 3 API error: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
      }

      const data = await response.json();
      const imageUrl = data.data?.[0]?.url;

      if (!imageUrl) {
        throw new Error('No image URL returned from DALL-E 3');
      }

      return imageUrl;
    } catch (error) {
      console.error('Error generating image with DALL-E 3:', error);
      throw error;
    }
  }

  /**
   * Create analysis prompt based on edit options
   */
  private createAnalysisPrompt(options: GPT5EditOptions): string {
    const { mode, brightness, contrast, saturation, blur, rotation, customPrompt } = options;

    let basePrompt = 'Analyze this image carefully and create a detailed DALL-E 3 prompt to recreate it with the following modifications:\n\n';

    switch (mode) {
      case 'enhance':
        basePrompt += `- Enhance the overall quality and clarity
- Improve sharpness and detail
- Optimize colors and lighting
- Maintain the original composition and subject`;
        break;

      case 'adjust':
        const adjustments: string[] = [];
        if (brightness !== undefined && brightness !== 100) {
          adjustments.push(`- ${brightness > 100 ? 'Increase' : 'Decrease'} brightness by ${Math.abs(brightness - 100)}%`);
        }
        if (contrast !== undefined && contrast !== 100) {
          adjustments.push(`- ${contrast > 100 ? 'Increase' : 'Decrease'} contrast by ${Math.abs(contrast - 100)}%`);
        }
        if (saturation !== undefined && saturation !== 100) {
          adjustments.push(`- ${saturation > 100 ? 'Increase' : 'Decrease'} color saturation by ${Math.abs(saturation - 100)}%`);
        }
        if (blur !== undefined && blur > 0) {
          adjustments.push(`- Apply ${blur}px blur effect`);
        }
        if (rotation !== undefined && rotation !== 0) {
          adjustments.push(`- Rotate the composition by ${rotation} degrees`);
        }
        basePrompt += adjustments.length > 0 ? adjustments.join('\n') : '- Maintain the original appearance';
        break;

      case 'transform':
        basePrompt += `- Transform the style while keeping the subject recognizable
- Apply artistic enhancement
- Improve composition and visual appeal
- Maintain key elements of the original`;
        break;

      case 'effects':
        basePrompt += `- Apply creative visual effects
- Enhance with professional filters
- Add depth and dimension
- Create a polished, professional result`;
        break;

      case 'custom':
        basePrompt += customPrompt || '- Apply general improvements';
        break;

      default:
        basePrompt += '- Apply general enhancements to improve the image';
    }

    basePrompt += '\n\nIMPORTANT: Your response should ONLY be a detailed DALL-E 3 prompt that describes the edited image. Do not include explanations or commentary, just the prompt itself.';

    return basePrompt;
  }

  /**
   * Create variations of an image
   */
  async createVariations(
    imageUrl: string,
    count: number = 3
  ): Promise<string[]> {
    this.ensureApiKey();
    try {
      console.log('Creating variations with GPT-4o + DALL-E 3');

      // Analyze the original image
      const analysisPrompt = 'Describe this image in detail, including composition, colors, style, and mood. Then create 3 different DALL-E 3 prompts for variations that maintain the core subject but explore different styles, angles, or color schemes.';

      const variationPrompts = await this.analyzeImageWithGPT4o(imageUrl, analysisPrompt);

      // Parse and generate variations (simplified - in production, parse individual prompts)
      const variations: string[] = [];

      for (let i = 0; i < count; i++) {
        const variationPrompt = `${variationPrompts} - Variation ${i + 1}`;
        const variationUrl = await this.generateEditedImageWithDALLE(variationPrompt);
        variations.push(variationUrl);
      }

      return variations;
    } catch (error) {
      console.error('Error creating variations:', error);
      throw error;
    }
  }
}

let _gpt5ImageEditorInstance: GPT5ImageEditorService | null = null;

function getGPT5ImageEditor(): GPT5ImageEditorService {
  if (!_gpt5ImageEditorInstance) {
    _gpt5ImageEditorInstance = new GPT5ImageEditorService();
  }
  return _gpt5ImageEditorInstance;
}

export const gpt5ImageEditor = {
  isAvailable: () => hasApiKey('openai'),
  editImage: (imageUrl: string, options: GPT5EditOptions) =>
    getGPT5ImageEditor().editImage(imageUrl, options),
  createVariations: (imageUrl: string, count?: number) =>
    getGPT5ImageEditor().createVariations(imageUrl, count),
};

export const editImageWithGPT5 = (
  imageUrl: string,
  options: GPT5EditOptions
): Promise<GPT5EditResult> => {
  return getGPT5ImageEditor().editImage(imageUrl, options);
};

export const createVariationsWithGPT5 = (
  imageUrl: string,
  count?: number
): Promise<string[]> => {
  return getGPT5ImageEditor().createVariations(imageUrl, count);
};

export const isGPT5EditorAvailable = (): boolean => hasApiKey('openai');
